name: lunar-e2e-pin-rotation-08c9721c3
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 08c9721c3'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-08c9721c3'
    runs-on: localdev-e2e-test-37300970172-1-github-3-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 08c9721c3'
